name: Sync from upstream repository

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write 

jobs:
  sync-fork:
    runs-on: ubuntu-latest

    steps:
      - name: Check out your fork
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "[email protected]"

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/firehol/blocklist-ipsets.git
          git fetch upstream

      - name: Merge upstream changes
        run: |
          git checkout master
          git merge upstream/master

      - name: Push changes to fork
        run: git push origin HEAD:master
